# This is a basic workflow to help you get started with Actions

name: Create Secrets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: gliech/create-github-secret-action@v1
          with:
            location: abhinavneu/AzureBlueprints
            name: NEW_RG
            value: ${{ secrets.RG_NAME }}
            pa_token: ${{ secrets.PA_TOKEN }}
            
        - uses: gliech/create-github-secret-action@v1
          with:
            location: abhinavneu/neu-one-da-accelerator-Synapse
            name: PA_TOKEN
            value: ${{ secrets.PA_TOKEN }}
            pa_token: ${{ secrets.PA_TOKEN }}
