AzureStorageAccountName: neusbxcusdaadl01
AzureStorageContainerName: framework
KeyVaultName: neu-sbx-cus-da-kv-01
SparkPoolName: neusbxspark01
DataBricksURL: https://adb-8992693674834351.11.azuredatabricks.net
DataBricksClusterID: 0831-140718-icky488
AzureSqlDW_properties_typeProperties_connectionString_secretName: DataWarehouseConnectionString
AzureSqlFrameworkDB_properties_typeProperties_connectionString_secretName: FrameworkConnectionString
AzureSqlRetailService_properties_typeProperties_connectionString_secretName: RetailConnectionString
DataWarehouseSQL_properties_typeProperties_connectionString_secretName: DataWarehouseConnectionString
SmiStageSqlDatabase_properties_typeProperties_connectionString_secretName: StageConnectionString
SuperMasterDatabricksWeekly_properties_SuperMasterDatabricks_parameters_PipelineScheduleName: Daily
SuperMasterParquetWeekly_properties_SuperMasterParquet_parameters_PipelineScheduleName: Daily
SuperMasterSQLWeekly_properties_SuperMasterSQL_parameters_PipelineScheduleName: Daily
SendAlertLogicAppsHTTPUrl: https://prod-07.centralus.logic.azure.com:443/workflows/c1c50335f6654e8c848eeaf270415b16/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=3-rz87HVZU6XrAk19uBNKgwKtIPtiG4DWDoNJiWiN69